// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntifrrkerjzlywiaxtue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50aWZycmtlcmp6bHl3aWF4dHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzkzMTAsImV4cCI6MjA1OTI1NTMxMH0.cpqKr8e5LFX1ljHMcOEUtWjmlhLO35483SW2U3FgEp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);